export const POST_ACTIONS = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCHED_POSTS: "FETCHED_POSTS",
    FAILED_FETCH_POSTS: "FAILED_FETCH_POSTS",

    FETCH_CREATE_POSTS: "FETCH_CREATE_POSTS",
    FETCHED_CREATE_POSTS: "FETCHED_CREATE_POSTS",
    FAILED_FETCH_CREATE_POSTS: "FAILED_FETCH_CREATE_POSTS",
};

export const STATE_STATUS = {
    SERVER_ERROR: "SERVER_ERROR",
    UNFETCHED: "UNFETCHED",
    FETCHING: "FETCHING",
    FETCHED: "FETCHED",
    FAILED_FETCH: "FAILED_FETCH"
}